name: Create Issue

on:
  push:
    branches: [main]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v4
        with:
          script: |
            const title = "New issue title";
            const body = "New issue body";
            const owner = "your-username";
            const repo = "your-repo-name";

            const { data } = await github.issues.create({
              owner,
              repo,
              title,
              body
            });

            console.log(`Created issue: ${data.html_url}`);
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
