name: Create Issue
on:
  push:
    branches:
      - main
jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v5
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue = await octokit.issues.create({
              owner,
              repo,
              title: 'New Issue Title',
              body: 'This is the body of the issue',
            });
            console.log(`Created issue #${issue.data.number}`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
