name: Create Issue
on:
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: repo-sync/github-issues@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          title: Issue Title
          body: |
            This is the body of the issue.
            You can add multiple lines of text here.
          labels: |
            bug
            enhancement
         
