name: Create Issue
on:
  push:
    branches:
      - master

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Issue
      uses: peter-evans/create-issue@v2.5.0
      with:
        title: Issue Title
        body: |
          This is the issue description. You can use Markdown syntax here.
          - [ ] Task 1
          - [ ] Task 2
        labels: |
          bug
          enhancement

