name: Create Issue on Commit

on:
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Issue
        uses: actions/github-script@v4
        with:
          script: |
            const title = 'Issue Title';
            const body = 'Issue Description';
            const octokit = require('@octokit/rest')();
            octokit.issues.create({
              owner: '${{ github.repository_owner }}',
              repo: '${{ github.repository }}',
              title: title,
              body: body
            });

        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
